"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { FileSignature, Save } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { LoadingScreen } from "@/components/loading-screen";
import { Alert, PageHeader, SectionHeader } from "@/components/ui";
import { FINANCING_OPTIONS, MOUNTING_OPTIONS, PRODUCT_OPTIONS } from "@/lib/contracts";
import { supabase } from "@/lib/supabase";
import type { Lead } from "@/lib/types";
import { useAuth } from "@/lib/use-auth";

const initial = { contract_number:"", signed_at:new Date().toISOString().slice(0,10), customer_name:"", phone:"", email:"", postal_code:"", city:"", street:"", house_number:"", financing:"gotowka", credit_amount:"", product_type:"PV", pv_power_kwp:"", storage_capacity_kwh:"", panel_power_wp:"", panels_count:"", has_inverter:true, inverter_power_kw:"", multiple_mounting_locations:false, mounting_locations:[] as string[], gross_amount:"", backup_power:false, optimizer_count:"0", surge_protection:false, grounding:false, additional_notes:"" };

export default function NewContractPage() {
  const { loading, profile, session } = useAuth(["owner","admin","menadzer","handlowiec"]);
  const router = useRouter(); const [leadId,setLeadId] = useState(""); const [contractId,setContractId] = useState("");
  const [form,setForm] = useState(initial); const [lead,setLead] = useState<Lead|null>(null); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  const set = (key:keyof typeof initial, value:unknown) => setForm((current)=>({...current,[key]:value}));

  useEffect(()=>{ const query=new URLSearchParams(window.location.search);setLeadId(query.get("leadId")||"");setContractId(query.get("contractId")||""); },[]);
  useEffect(()=>{if(!session||!contractId)return;fetch(`/api/contracts?id=${contractId}`,{headers:{Authorization:`Bearer ${session.access_token}`}}).then(r=>r.json()).then(({contract})=>{if(!contract)return;setForm((current)=>({...current,...Object.fromEntries(Object.keys(current).filter(key=>key in contract).map(key=>[key,contract[key]]))}));});},[session,contractId]);
  useEffect(()=>{ if(!profile||!leadId)return; supabase.from("leads").select("*").eq("id",leadId).eq("crm_environment",profile.crm_environment).single().then(({data})=>{ if(!data){setError("Nie znaleziono leada.");return;} const next=data as Lead; setLead(next); setForm((current)=>({...current,customer_name:next.full_name,phone:next.phone,postal_code:next.postal_code||"",street:next.address||"",contract_number:next.contract_number||""})); }); },[profile,leadId]);
  if(loading||!profile)return <LoadingScreen/>;
  const isPV=form.product_type.includes("PV"), isME=form.product_type.includes("ME"), inverterRequired=form.product_type!=="ME"||form.has_inverter;
  async function submit(event:FormEvent){event.preventDefault();if(!session||(!lead&&!contractId))return;setBusy(true);setError("");const response=await fetch("/api/contracts",{method:contractId?"PATCH":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(contractId?{id:contractId,contract_data:form}:{...form,lead_id:lead!.id})});const body=await response.json();if(!response.ok){setError(body.error||"Nie udało się zapisać umowy.");setBusy(false);return;}router.replace(`/realizacja/${contractId||body.contract.id}`);}
  const field=(key:keyof typeof initial,label:string,type="text",required=true)=><label><span className="label">{label}</span><input className="field" type={type} value={String(form[key])} onChange={(e)=>set(key,e.target.value)} required={required}/></label>;
  return <AppShell profile={profile}><div className="grid gap-5"><PageHeader title={contractId?"Edycja umowy":"Nowa umowa"} description={contractId?"Zmień dane umowy. Zmiany nie nadpisują danych źródłowego leada.":"Dane klienta zostały pobrane z leada. Sprawdź je i uzupełnij parametry sprzedaży."}/><form onSubmit={submit} className="grid gap-5">
    {error?<Alert tone="danger">{error}</Alert>:null}
    <section className="app-card"><SectionHeader icon={FileSignature} title="Klient i umowa" description="Wszystkie pola są wymagane. Dane można poprawić bez zmiany leada." tone="sky"/><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{field("contract_number","Numer umowy")}{field("signed_at","Data podpisania","date")}{field("customer_name","Imię i nazwisko")}{field("phone","Numer telefonu")}{field("email","E-mail","email")}{field("postal_code","Kod pocztowy")}{field("city","Miejscowość")}{field("street","Ulica")}{field("house_number","Numer domu")}</div></section>
    <section className="app-card"><SectionHeader icon={FileSignature} title="Finansowanie i sprzedany zestaw" tone="leaf"/><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label><span className="label">Finansowanie</span><select className="field" value={form.financing} onChange={(e)=>set("financing",e.target.value)}>{FINANCING_OPTIONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{form.financing!=="gotowka"?field("credit_amount","Kwota kredytu brutto","number"):null}<label><span className="label">Co sprzedane</span><select className="field" value={form.product_type} onChange={(e)=>{set("product_type",e.target.value);set("mounting_locations",[]);set("multiple_mounting_locations",false)}}>{PRODUCT_OPTIONS.map(v=><option key={v}>{v}</option>)}</select></label>{field("gross_amount","Kwota brutto","number")}</div>
    <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{isPV?field("pv_power_kwp","Moc PV (kWp)","number"):null}{isPV?field("panel_power_wp","Moc panelu (Wp)","number"):null}{isPV?field("panels_count","Liczba paneli","number"):null}{isME?field("storage_capacity_kwh","Moc / pojemność ME (kWh)","number"):null}{form.product_type==="ME"?<label className="flex items-center gap-2 rounded-lg border border-line p-3"><input type="checkbox" checked={form.has_inverter} onChange={(e)=>set("has_inverter",e.target.checked)}/> Magazyn z falownikiem</label>:null}{inverterRequired?field("inverter_power_kw","Moc falownika (kW)","number"):null}</div></section>
    <section className="app-card"><SectionHeader icon={FileSignature} title="Montaż i wyposażenie" tone="solar"/>{form.product_type==="ME"?<label className="mt-4 block max-w-xl"><span className="label">Miejsce montażu magazynu</span><input className="field" value={form.mounting_locations[0]||""} onChange={e=>{set("mounting_locations",[e.target.value]);set("multiple_mounting_locations",false)}} placeholder="np. kotłownia, piwnica, pomieszczenie w garażu" required/><span className="mt-1 block text-xs text-muted">Wpisz konkretne pomieszczenie, w którym stanie magazyn energii.</span></label>:<><label className="mt-4 flex items-center gap-2"><input type="checkbox" checked={form.multiple_mounting_locations} onChange={(e)=>{set("multiple_mounting_locations",e.target.checked);if(!e.target.checked&&form.mounting_locations.length>1)set("mounting_locations",form.mounting_locations.slice(0,1));}}/> Wiele miejsc montażu PV</label><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4">{MOUNTING_OPTIONS.map(location=><label key={location} className="flex items-center gap-2 rounded-lg border border-line p-3"><input type={form.multiple_mounting_locations?"checkbox":"radio"} name="mounting" checked={form.mounting_locations.includes(location)} onChange={()=>set("mounting_locations",form.multiple_mounting_locations?(form.mounting_locations.includes(location)?form.mounting_locations.filter(x=>x!==location):[...form.mounting_locations,location]):[location])}/>{location}</label>)}</div></>}<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{field("optimizer_count","Liczba optymalizatorów","number",false)}{[["backup_power","Back-up"],["surge_protection","Ochrona przepięciowa"],["grounding","Uziemienie"]].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-lg border border-line p-3"><input type="checkbox" checked={Boolean(form[key as keyof typeof initial])} onChange={(e)=>set(key as keyof typeof initial,e.target.checked)}/>{label}</label>)}</div><label className="mt-4 block"><span className="label">Uwagi dodatkowe</span><textarea className="field min-h-28" value={form.additional_notes} onChange={(e)=>set("additional_notes",e.target.value)}/></label></section>
    <div className="flex justify-end"><button className="btn-primary" disabled={busy}><Save className="h-4 w-4"/>{busy?"Zapisywanie…":"Zapisz umowę"}</button></div>
  </form></div></AppShell>;
}
